# Generated by Django 5.2.17 on 2025-01-16 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAPIKey',
        ),
    ]
