# Generated by Django 5.2.3 on 2025-06-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limit',
            name='file_limit_per_source',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='limit',
            name='private_source_limit',
            field=models.IntegerField(default=3),
        ),
    ]
