# Generated by Django 5.2.3 on 2025-06-29 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_limit_file_limit_per_source_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='limit',
            options={'verbose_name': '使用方案', 'verbose_name_plural': '使用方案'},
        ),
    ]
