# Generated by Django 5.2.3 on 2025-06-26 01:28

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_id', models.IntegerField(unique=True, verbose_name='資料集識別碼')),
                ('url', models.URLField(verbose_name='資料集網址')),
                ('name', models.CharField(max_length=255, verbose_name='資料集名稱')),
                ('category', models.CharField(db_index=True, max_length=100, verbose_name='服務分類')),
                ('description', models.TextField(blank=True, null=True, verbose_name='資料集描述')),
                ('department', models.CharField(max_length=100, verbose_name='提供機關')),
                ('update_frequency', models.CharField(max_length=100, verbose_name='更新頻率')),
                ('license', models.CharField(max_length=100, verbose_name='授權方式')),
                ('price', models.CharField(max_length=100, verbose_name='計費方式')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='聯絡人姓名')),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='聯絡人電話')),
                ('upload_time', models.DateTimeField(blank=True, null=True, verbose_name='上架日期')),
                ('update_time', models.DateTimeField(blank=True, null=True, verbose_name='詮釋資料更新時間')),
                ('description_embeddings', pgvector.django.vector.VectorField(dimensions=1536, help_text='基於 rag_description 欄位並使用 OpenAI text-embedding-3-small 產生向量。')),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['description_embeddings'], m=16, name='crawlers_desc_emb_hnsw_idx', opclasses=['vector_l2_ops'])],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_download_url', models.URLField(verbose_name='資料下載網址')),
                ('original_format', models.CharField(choices=[('csv', 'Csv'), ('json', 'Json'), ('xml', 'Xml')], max_length=20, verbose_name='原始檔案格式')),
                ('encoding', models.CharField(max_length=50, verbose_name='編碼格式')),
                ('content_md5', models.CharField(max_length=64, unique=True, verbose_name='檔案內容 MD5')),
                ('table_name', models.CharField(help_text='在 GovData 資料庫中的資料表名稱', max_length=255, unique=True, verbose_name='對應資料表名稱')),
                ('database_name', models.CharField(default='InvestmentAndFinancialManagementGovData', help_text='在 GovData 資料庫中的資料庫名稱', max_length=255, verbose_name='對應資料庫名稱')),
                ('column_mapping_list', models.JSONField(help_text='欄位對應列表，格式為 [[a, 欄位描述], [b, 欄位描述], ...]', verbose_name='欄位對應列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawlers.dataset', verbose_name='所屬資料集')),
            ],
            options={
                'verbose_name': '檔案',
                'verbose_name_plural': '檔案',
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_id', models.IntegerField()),
                ('subject', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('symptom', models.CharField(max_length=255)),
                ('question', models.TextField(db_index=True)),
                ('answer', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('question_time', models.DateTimeField(help_text='網站上的患者提問時間。')),
                ('answer_time', models.DateTimeField(help_text='網站上的醫師回答時間。')),
                ('question_embeddings', pgvector.django.vector.VectorField(dimensions=1536, help_text='基於 question 欄位並使用 OpenAI text-embedding-3-small 產生向量。')),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['question_embeddings'], m=16, name='crawlers_symp_q_emb_hnsw_idx', opclasses=['vector_l2_ops'])],
            },
        ),
    ]
