version: '3.8'

services:
  # PostgreSQL 資料庫
  postgres:
    image: pgvector/pgvector:pg15
    container_name: datahunter_postgres
    environment:
      POSTGRES_DB: DataHunter
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Redis 快取和 Channel Layer
  redis:
    image: redis:7-alpine
    container_name: datahunter_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Django Web 應用
  web:
    build: .
    container_name: datahunter_web
    command: daphne -b 0.0.0.0 -p 8000 DataHunter.asgi:application
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=your-secret-key-here
      - POSTGRES_DB=DataHunter
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0,your-domain.com
    depends_on:
      - postgres
      - redis
    volumes:
      - ./staticfiles:/app/staticfiles
    restart: unless-stopped

  # Celery Worker
  celery:
    build: .
    container_name: datahunter_celery
    command: celery -A DataHunter worker --loglevel=info
    environment:
      - DEBUG=False
      - SECRET_KEY=your-secret-key-here
      - POSTGRES_DB=DataHunter
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: 