version: "3.8"

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: ankane/pgvector
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: DataHunter
    ports:
      - "5432:5432"
    volumes:
      - ${POSTGRES_VOLUME:-./Datas/PostgresVector}:/var/lib/postgresql/data

  chrome:
    image: selenium/node-chrome:latest
    container_name: chrome
    platform: linux/amd64
    shm_size: "2gb"
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=4
      - SE_NODE_MAX_INSTANCES=4
      - SE_NODE_SESSION_TIMEOUT=600

  selenium-hub:
    image: selenium/hub:latest
    platform: linux/amd64
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"