# Generated by Django 5.2.3 on 2025-06-24 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at'], 'verbose_name': '對話訊息', 'verbose_name_plural': '對話訊息'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': '對話會話', 'verbose_name_plural': '對話會話'},
        ),
    ]
