# Generated by Django 5.2.3 on 2025-06-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_alter_message_options_alter_session_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='軟刪除標記'),
        ),
    ]
