# Generated by Django 5.2.3 on 2025-06-25 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_message_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated_at'], 'verbose_name': '對話訊息', 'verbose_name_plural': '對話訊息'},
        ),
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_messages', to='conversations.message'),
        ),
    ]
