# Generated by Django 5.2.3 on 2025-06-25 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0005_alter_message_options_message_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='citations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
