"""
Crawlers 應用的 Prompt 模板包
"""

from .symptom import SYMPTOM_SYSTEM_PROMPT, SYMPTOM_VARIETY_PROMPTS, SYMPTOM_SUGGESTION_PROMPT_TEMPLATE
from .gov_datas import GOV_DATA_SYSTEM_PROMPT, GOV_DATA_VARIETY_PROMPTS, GOV_DATA_SUGGESTION_PROMPT_TEMPLATE

__all__ = [
    'SYMPTOM_SYSTEM_PROMPT',
    'SYMPTOM_VARIETY_PROMPTS', 
    'SYMPTOM_SUGGESTION_PROMPT_TEMPLATE',
    'GOV_DATA_SYSTEM_PROMPT',
    'GOV_DATA_VARIETY_PROMPTS',
    'GOV_DATA_SUGGESTION_PROMPT_TEMPLATE',
] 