# Generated by Django 5.2 on 2025-06-12 05:49

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_id', models.IntegerField()),
                ('department', models.CharField(max_length=255)),
                ('symptom', models.CharField(max_length=255)),
                ('question', models.TextField(db_index=True)),
                ('answer', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('question_time', models.DateTimeField(help_text='網站上的患者提問時間。')),
                ('answer_time', models.DateTimeField(help_text='網站上的醫師回答時間。')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question_embeddings', pgvector.django.vector.VectorField(dimensions=1536, help_text='基於 question 欄位並使用 OpenAI text-embedding-3-small 產生向量。')),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['question_embeddings'], m=16, name='symptom_q_emb_hnsw_idx', opclasses=['vector_l2_ops'])],
            },
        ),
    ]
