# Generated by Django 5.2 on 2025-04-28 10:15

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
    ]
