# Generated by Django 5.2 on 2025-06-13 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='subject',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
