# Generated by Django 5.2.3 on 2025-06-14 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0002_symptom_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='created_at',
        ),
    ]
