# Generated by Django 5.2 on 2025-04-28 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0003_symptom_age_symptom_answer_symptom_answer_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symptom',
            old_name='question_embedding',
            new_name='question_embeddings',
        ),
    ]
