# Generated by Django 5.2.3 on 2025-06-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0003_remove_symptom_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
