# Generated by Django 5.2.3 on 2025-06-15 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0004_symptom_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='age',
        ),
    ]
