# Generated by Django 5.2 on 2025-04-28 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0004_rename_question_embedding_symptom_question_embeddings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='age',
        ),
    ]
