# Generated by Django 5.2 on 2025-06-12 03:19

import django.contrib.postgres.indexes
import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptoms', '0005_remove_symptom_age'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='symptom',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['question_embeddings'], m=16, name='symptom_q_emb_hnsw_idx', opclasses=['vector_l2_ops']),
        ),
        migrations.AddIndex(
            model_name='symptom',
            index=django.contrib.postgres.indexes.GinIndex(fields=['question'], name='symptom_q_trgm_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
