# Generated by Django 5.2 on 2025-06-12 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAPIKey',
            fields=[
                ('id', models.CharField(editable=False, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('prefix', models.CharField(editable=False, max_length=8, unique=True)),
                ('hashed_key', models.CharField(editable=False, max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('revoked', models.BooleanField(blank=True, default=False, help_text='If the API key is revoked, clients cannot use it anymore. (This cannot be undone.)')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Once API key expires, clients cannot use it anymore.', null=True, verbose_name='Expires')),
                ('name', models.CharField(help_text='API Key 的名稱，方便識別用途', max_length=100, verbose_name='Key 名稱')),
                ('expires_at', models.DateTimeField(blank=True, help_text='API Key 的到期時間，留空表示永不到期', null=True, verbose_name='到期時間')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='最後一次使用此 API Key 的時間', null=True, verbose_name='最後使用時間')),
                ('is_active', models.BooleanField(default=True, help_text='此 API Key 是否啟用', verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '使用者 API Key',
                'verbose_name_plural': '使用者 API Keys',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
