# Generated by Django 5.2.3 on 2025-06-27 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ['-created_at'], 'verbose_name': '自建資料源', 'verbose_name_plural': '自建資料源'},
        ),
        migrations.AlterModelOptions(
            name='sourcefile',
            options={'ordering': ['-created_at'], 'verbose_name': '資料源檔案', 'verbose_name_plural': '資料源檔案'},
        ),
        migrations.AlterModelOptions(
            name='sourcefilechunk',
            options={'verbose_name': '資料源檔案片段', 'verbose_name_plural': '資料源檔案片段'},
        ),
        migrations.AlterModelOptions(
            name='sourcefiletable',
            options={'verbose_name': '資料源檔案表格', 'verbose_name_plural': '資料源檔案表格'},
        ),
    ]
