# Generated by Django 5.2.3 on 2025-06-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_alter_source_options_alter_sourcefile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcefile',
            name='format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('json', 'JSON'), ('xml', 'XML')], max_length=10),
        ),
    ]
