# Generated by Django 5.2.3 on 2025-06-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_alter_sourcefile_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcefile',
            name='failed_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
