# Generated by Django 5.2.3 on 2025-06-29 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_sourcefile_failed_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sourcefile',
            name='is_deleted',
        ),
    ]
