# Generated by Django 5.2.3 on 2025-06-29 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0005_remove_sourcefile_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='is_deleted',
        ),
    ]
