# Generated by Django 5.2.3 on 2025-06-13 16:17

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_id', models.IntegerField(unique=True, verbose_name='資料集識別碼')),
                ('url', models.URLField(verbose_name='資料集網址')),
                ('name', models.CharField(max_length=255, verbose_name='資料集名稱')),
                ('category', models.CharField(max_length=100, verbose_name='服務分類')),
                ('description', models.TextField(blank=True, null=True, verbose_name='資料集描述')),
                ('columns_description', models.JSONField(verbose_name=models.CharField(max_length=100))),
                ('department', models.CharField(max_length=100, verbose_name='提供機關')),
                ('update_frequency', models.CharField(max_length=100, verbose_name='更新頻率')),
                ('license', models.CharField(max_length=100, verbose_name='授權方式')),
                ('price', models.CharField(max_length=100, verbose_name='計費方式')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='聯絡人姓名')),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='聯絡人電話')),
                ('upload_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='上架日期')),
                ('update_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='詮釋資料更新時間')),
                ('rag_description', models.TextField(blank=True, null=True, verbose_name='重構內容')),
                ('description_embeddings', pgvector.django.vector.VectorField(dimensions=1536, help_text='基於 rag_description 欄位並使用 OpenAI text-embedding-3-small 產生向量。')),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['description_embeddings'], m=16, name='description_embeddings_hnsw_idx', opclasses=['vector_l2_ops'])],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_download_url', models.URLField(verbose_name='資料下載網址')),
                ('filename', models.CharField(max_length=255, verbose_name='檔案名稱')),
                ('encoding', models.CharField(max_length=50, verbose_name='編碼格式')),
                ('format', models.CharField(choices=[('csv', 'Csv'), ('json', 'Json'), ('xml', 'Xml')], max_length=20, verbose_name='檔案格式')),
                ('content_md5', models.CharField(max_length=64, unique=True, verbose_name='檔案內容 MD5')),
                ('gridfs_id', models.CharField(max_length=100, verbose_name='GridFS ID')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='gov_datas.dataset', verbose_name='所屬資料集')),
            ],
        ),
    ]
