# Generated by Django 5.2.3 on 2025-06-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov_datas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='format',
            field=models.CharField(choices=[('csv', 'Csv')], max_length=20, verbose_name='檔案格式'),
        ),
    ]
