# Generated by Django 5.2.3 on 2025-06-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov_datas', '0002_alter_file_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='original_formats',
            field=models.CharField(blank=True, choices=[('csv', 'Csv'), ('json', 'Json'), ('xml', 'Xml')], help_text='記錄合併前的原始格式，如：csv,json,xml', max_length=20, null=True, verbose_name='原始檔案格式'),
        ),
        migrations.AlterField(
            model_name='file',
            name='format',
            field=models.CharField(default='csv', max_length=20, verbose_name='檔案格式'),
        ),
    ]
