# Generated by Django 5.2.3 on 2025-06-14 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov_datas', '0009_remove_dataset_table_list_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='column_count',
        ),
        migrations.RemoveField(
            model_name='file',
            name='row_count',
        ),
        migrations.RemoveField(
            model_name='file',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='file',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gov_datas.dataset', verbose_name='所屬資料集'),
        ),
        migrations.AlterField(
            model_name='file',
            name='table_name',
            field=models.CharField(help_text='在 GovData 資料庫中的資料表名稱', max_length=255, unique=True, verbose_name='對應資料表名稱'),
        ),
    ]
