# Generated by Django 5.2.3 on 2025-06-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov_datas', '0011_file_database_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='column_mapping_list',
            field=models.JSONField(default=[], help_text='欄位對應列表，格式為 [[a, 欄位描述], [b, 欄位描述], ...]', verbose_name='欄位對應列表'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataset',
            name='columns_description',
            field=models.JSONField(verbose_name='欄位描述'),
        ),
    ]
